-- Insert 10 dummy milestones (Step 3)
-- Note: Using the first 10 project_ids and user_ids from the previous inserts
INSERT INTO milestones (
    milestone_name,
    milestone_description,
    target_date,
    actual_date,
    status,
    priority,
    milestone_type,
    project_id,
    owner_id,
    completion_percentage,
    deliverables,
    success_criteria,
    dependencies,
    risks,
    budget_allocated,
    budget_spent,
    notes
) VALUES 
(
    'Project Kickoff Complete',
    'Complete project initiation, team formation, and requirement gathering',
    '2024-02-15',
    '2024-02-14',
    'Completed',
    'High',
    'Review',
    (SELECT project_id FROM projects WHERE project_name = 'E-Commerce Platform'),
    (SELECT user_id FROM users WHERE username = 'john_doe'),
    100.00,
    ARRAY['Project charter', 'Team assignments', 'Requirements document'],
    'All stakeholders approve project charter and requirements',
    ARRAY['Stakeholder availability', 'Budget approval'],
    ARRAY['Delayed stakeholder approval'],
    15000.00,
    14500.00,
    'Kickoff completed ahead of schedule with full stakeholder buy-in'
),
(
    'MVP Development Complete',
    'Complete minimum viable product for mobile banking app',
    '2024-08-31',
    NULL,
    'In Progress',
    'Critical',
    'Release',
    (SELECT project_id FROM projects WHERE project_name = 'Mobile Banking App'),
    (SELECT user_id FROM users WHERE username = 'sarah_wilson'),
    65.00,
    ARRAY['Core banking features', 'Security implementation', 'User authentication'],
    'MVP passes security audit and user acceptance testing',
    ARRAY['Security clearance', 'Banking API integration'],
    ARRAY['Regulatory compliance delays', 'Security vulnerabilities'],
    80000.00,
    52000.00,
    'Security implementation taking longer than expected'
),
(
    'Data Pipeline Architecture',
    'Design and implement core data processing pipeline',
    '2024-06-30',
    NULL,
    'Planned',
    'Medium',
    'Delivery',
    (SELECT project_id FROM projects WHERE project_name = 'Data Analytics Dashboard'),
    (SELECT user_id FROM users WHERE username = 'david_kim'),
    0.00,
    ARRAY['Data pipeline design', 'ETL processes', 'Data warehouse setup'],
    'Pipeline processes 1M+ records with <5 second latency',
    ARRAY['Data source access', 'Infrastructure provisioning'],
    ARRAY['Data quality issues', 'Performance bottlenecks'],
    35000.00,
    0.00,
    'Waiting for data source agreements to be finalized'
),
(
    'HR Core Modules Release',
    'Release employee management and payroll modules',
    '2024-07-15',
    '2024-07-20',
    'Completed',
    'Medium',
    'Release',
    (SELECT project_id FROM projects WHERE project_name = 'HR Management System'),
    (SELECT user_id FROM users WHERE username = 'mike_chen'),
    100.00,
    ARRAY['Employee database', 'Payroll system', 'Benefits management'],
    'All core HR functions operational and tested',
    ARRAY['Database migration', 'Legacy system integration'],
    ARRAY['Data migration issues'],
    40000.00,
    38500.00,
    'Delivered 5 days behind schedule due to integration complexities'
),
(
    'IoT Device Integration',
    'Complete integration with major IoT device manufacturers',
    '2024-09-30',
    NULL,
    'Planned',
    'High',
    'Delivery',
    (SELECT project_id FROM projects WHERE project_name = 'IoT Monitoring Platform'),
    (SELECT user_id FROM users WHERE username = 'robert_garcia'),
    0.00,
    ARRAY['Device protocols', 'Data collection APIs', 'Real-time monitoring'],
    'Support for 10+ device types with real-time data collection',
    ARRAY['Vendor partnerships', 'Protocol standardization'],
    ARRAY['Vendor delays', 'Protocol compatibility issues'],
    95000.00,
    0.00,
    'Project in planning phase, vendor negotiations ongoing'
),
(
    'AI Features Beta',
    'Release beta version of AI-powered content recommendation',
    '2024-10-15',
    NULL,
    'In Progress',
    'High',
    'Release',
    (SELECT project_id FROM projects WHERE project_name = 'Social Media App'),
    (SELECT user_id FROM users WHERE username = 'emily_taylor'),
    30.00,
    ARRAY['ML models', 'Recommendation engine', 'A/B testing framework'],
    'AI recommendations improve user engagement by 25%',
    ARRAY['Training data collection', 'ML infrastructure'],
    ARRAY['Model accuracy issues', 'Scalability concerns'],
    60000.00,
    18000.00,
    'Initial ML models showing promising results in testing'
),
(
    'System Go-Live',
    'Complete system deployment and user training',
    '2024-08-20',
    '2024-08-18',
    'Completed',
    'Critical',
    'Release',
    (SELECT project_id FROM projects WHERE project_name = 'Inventory Management'),
    (SELECT user_id FROM users WHERE username = 'alex_rodriguez'),
    100.00,
    ARRAY['Production deployment', 'User training', 'Support documentation'],
    'System handles full warehouse operations without issues',
    ARRAY['User acceptance testing', 'Performance optimization'],
    ARRAY['User adoption resistance'],
    25000.00,
    23800.00,
    'Successfully deployed 2 days early, excellent user adoption'
),
(
    'Video Streaming Platform',
    'Implement video streaming capabilities and content management',
    '2024-09-01',
    NULL,
    'In Progress',
    'Medium',
    'Delivery',
    (SELECT project_id FROM projects WHERE project_name = 'Learning Management System'),
    (SELECT user_id FROM users WHERE username = 'jennifer_brown'),
    55.00,
    ARRAY['Video upload system', 'Streaming infrastructure', 'Content library'],
    'Support 1000+ concurrent video streams with HD quality',
    ARRAY['CDN setup', 'Video encoding pipeline'],
    ARRAY['Bandwidth costs', 'Video quality issues'],
    45000.00,
    24750.00,
    'Video encoding optimization in progress'
),
(
    'Security Audit Complete',
    'Complete comprehensive security audit and penetration testing',
    '2024-11-30',
    NULL,
    'Planned',
    'Critical',
    'Review',
    (SELECT project_id FROM projects WHERE project_name = 'Blockchain Wallet'),
    (SELECT user_id FROM users WHERE username = 'lisa_anderson'),
    0.00,
    ARRAY['Security assessment', 'Penetration testing', 'Compliance report'],
    'Pass all security requirements with zero critical vulnerabilities',
    ARRAY['Security framework selection', 'Third-party audit firm'],
    ARRAY['Security vulnerabilities', 'Compliance failures'],
    30000.00,
    0.00,
    'Project in planning phase, security requirements being defined'
),
(
    'Telemedicine Integration',
    'Integrate video consultation and appointment scheduling',
    '2024-08-15',
    NULL,
    'Delayed',
    'High',
    'Delivery',
    (SELECT project_id FROM projects WHERE project_name = 'Healthcare Portal'),
    (SELECT user_id FROM users WHERE username = 'maria_martinez'),
    25.00,
    ARRAY['Video consultation system', 'Appointment scheduler', 'Patient records integration'],
    'Support 500+ concurrent video consultations',
    ARRAY['Healthcare API integrations', 'Compliance approval'],
    ARRAY['HIPAA compliance complexity', 'Integration delays'],
    55000.00,
    13750.00,
    'Project on hold due to compliance review requirements'
);