-- Insert 10 dummy projects (Step 1)
INSERT INTO projects (
    project_name, 
    project_description, 
    start_date, 
    end_date, 
    status, 
    priority, 
    budget, 
    client_name, 
    project_type, 
    completion_percentage, 
    tags
) VALUES 
(
    'E-Commerce Platform', 
    'Building a modern e-commerce platform with microservices architecture', 
    '2024-01-15', 
    '2024-12-31', 
    'Active', 
    'High', 
    250000.00, 
    'TechCorp Solutions', 
    'Web Development', 
    35.50, 
    ARRAY['ecommerce', 'microservices', 'react']
),
(
    'Mobile Banking App', 
    'Secure mobile banking application for iOS and Android', 
    '2024-02-01', 
    '2024-11-30', 
    'Active', 
    'Critical', 
    180000.00, 
    'First National Bank', 
    'Mobile App', 
    28.75, 
    ARRAY['mobile', 'banking', 'security', 'fintech']
),
(
    'Data Analytics Dashboard', 
    'Real-time analytics dashboard for business intelligence', 
    '2024-03-10', 
    '2024-09-15', 
    'Planning', 
    'Medium', 
    120000.00, 
    'Analytics Inc', 
    'Data Analytics', 
    5.00, 
    ARRAY['analytics', 'dashboard', 'business intelligence']
),
(
    'HR Management System', 
    'Comprehensive HR management and payroll system', 
    '2024-01-20', 
    '2024-10-30', 
    'Active', 
    'Medium', 
    95000.00, 
    'HR Solutions Ltd', 
    'Enterprise Software', 
    42.25, 
    ARRAY['hr', 'payroll', 'management']
),
(
    'IoT Monitoring Platform', 
    'Platform for monitoring industrial IoT devices', 
    '2024-04-01', 
    '2025-03-31', 
    'Planning', 
    'High', 
    320000.00, 
    'Industrial Systems Corp', 
    'IoT Platform', 
    0.00, 
    ARRAY['iot', 'monitoring', 'industrial']
),
(
    'Social Media App', 
    'Next-generation social media platform with AI features', 
    '2024-02-15', 
    '2025-01-15', 
    'Active', 
    'High', 
    275000.00, 
    'Social Connect LLC', 
    'Mobile App', 
    22.80, 
    ARRAY['social media', 'ai', 'mobile']
),
(
    'Inventory Management', 
    'Automated inventory tracking and management system', 
    '2024-01-05', 
    '2024-08-20', 
    'Completed', 
    'Medium', 
    85000.00, 
    'Warehouse Solutions', 
    'Enterprise Software', 
    100.00, 
    ARRAY['inventory', 'automation', 'warehouse']
),
(
    'Learning Management System', 
    'Online learning platform with video streaming capabilities', 
    '2024-03-20', 
    '2024-12-10', 
    'Active', 
    'Medium', 
    140000.00, 
    'EduTech Academy', 
    'Web Development', 
    38.60, 
    ARRAY['education', 'lms', 'video streaming']
),
(
    'Blockchain Wallet', 
    'Secure cryptocurrency wallet with multi-chain support', 
    '2024-05-01', 
    '2025-02-28', 
    'Planning', 
    'Critical', 
    200000.00, 
    'CryptoSecure Inc', 
    'Blockchain', 
    0.00, 
    ARRAY['blockchain', 'cryptocurrency', 'security']
),
(
    'Healthcare Portal', 
    'Patient portal for healthcare providers with telemedicine features', 
    '2024-01-30', 
    '2024-11-15', 
    'On Hold', 
    'High', 
    165000.00, 
    'MediCare Systems', 
    'Healthcare', 
    15.30, 
    ARRAY['healthcare', 'telemedicine', 'patient portal']
);